Libraries

In [1]:
import sklearn as sk
from sklearn import datasets,model_selection
import numpy as np
import pandas as  pd
import matplotlib.pyplot as plt

Dataset

In [3]:
# Download the iris dataset from a public URL
import requests

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
response = requests.get(url)

# Save the dataset to a local file
with open("iris.csv", "w") as f:
    f.write(response.text)

# Load the dataset into a pandas DataFrame
iris = pd.read_csv('iris.csv', names=["sepal length", "sepal width", "petal length", "petal width", "class"])
iris # Our example dataset

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
# Split Train test dataset
train,test = sk.model_selection.train_test_split(iris,test_size=0.2,shuffle=True)

In [5]:
X=train.iloc[:,:-1].values
y=train.iloc[:,-1].values
print(X)
print(y)

[[5.6 2.8 4.9 2. ]
 [5.4 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [4.6 3.6 1.  0.2]
 [5.5 2.6 4.4 1.2]
 [7.9 3.8 6.4 2. ]
 [5.5 2.5 4.  1.3]
 [5.5 2.4 3.8 1.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [6.  2.2 5.  1.5]
 [5.4 3.9 1.3 0.4]
 [7.7 3.  6.1 2.3]
 [4.5 2.3 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [7.2 3.  5.8 1.6]
 [6.4 3.2 4.5 1.5]
 [5.1 3.8 1.5 0.3]
 [7.7 2.6 6.9 2.3]
 [5.1 3.8 1.6 0.2]
 [6.  2.7 5.1 1.6]
 [6.7 3.1 4.4 1.4]
 [6.4 3.1 5.5 1.8]
 [6.3 2.7 4.9 1.8]
 [4.9 3.1 1.5 0.1]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 5.1 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.2 1.2 0.2]
 [5.8 2.7 5.1 1.9]
 [6.3 2.5 5.  1.9]
 [5.6 2.9 3.6 1.3]
 [6.2 2.2 4.5 1.5]
 [5.8 2.6 4.  1.2]
 [5.8 4.  1.2 0.2]
 [5.  2.  3.5 1. ]
 [4.7 3.2 1.3 0.2]
 [5.  3.6 1.4 0.2]
 [4.4 3.  1.3 0.2]
 [6.  2.2 4.  1. ]
 [4.9 2.5 4.5 1.7]
 [5.1 3.5 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [5.7 2.8 4.5 1.3]
 [6.8 3.2 5.9 2.3]
 [5.5 2.4 3.7 1. ]
 [6.8 3.  5.5 2.1]
 [7.7 3.8 6.7 2.2]
 [6.  3.  4.8 1.8]
 [6.6 3.  4.4 1.4]
 [5.2 3.4 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [6.4 2.8 5.

In [6]:
train

sepal length  sepal width  petal length  petal width            class
121           5.6          2.8           4.9          2.0   Iris-virginica
10            5.4          3.7           1.5          0.2      Iris-setosa
36            5.5          3.5           1.3          0.2      Iris-setosa
22            4.6          3.6           1.0          0.2      Iris-setosa
90            5.5          2.6           4.4          1.2  Iris-versicolor
..            ...          ...           ...          ...              ...
9             4.9          3.1           1.5          0.1      Iris-setosa
139           6.9          3.1           5.4          2.1   Iris-virginica
24            4.8          3.4           1.9          0.2      Iris-setosa
13            4.3          3.0           1.1          0.1      Iris-setosa
107           7.3          2.9           6.3          1.8   Iris-virginica

[120 rows x 5 columns]

In [7]:
test

sepal length  sepal width  petal length  petal width            class
45            4.8          3.0           1.4          0.3      Iris-setosa
127           6.1          3.0           4.9          1.8   Iris-virginica
91            6.1          3.0           4.6          1.4  Iris-versicolor
108           6.7          2.5           5.8          1.8   Iris-virginica
29            4.7          3.2           1.6          0.2      Iris-setosa
124           6.7          3.3           5.7          2.1   Iris-virginica
69            5.6          2.5           3.9          1.1  Iris-versicolor
149           5.9          3.0           5.1          1.8   Iris-virginica
50            7.0          3.2           4.7          1.4  Iris-versicolor
116           6.5          3.0           5.5          1.8   Iris-virginica
125           7.2          3.2           6.0          1.8   Iris-virginica
40            5.0          3.5           1.3          0.3      Iris-setosa
54            6.5          2.8           4.6          1.5  Iris-versicolor
58            6.6          2.9           4.6          1.3  Iris-versicolor
98            5.1          2.5           3.0          1.1  Iris-versicolor
67            5.8          2.7           4.1          1.0  Iris-versicolor
145           6.7          3.0           5.2          2.3   Iris-virginica
103           6.3          2.9           5.6          1.8   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
120           6.9          3.2           5.7          2.3   Iris-virginica
95            5.7          3.0           4.2          1.2  Iris-versicolor
77            6.7          3.0           5.0          1.7  Iris-versicolor
132           6.4          2.8           5.6          2.2   Iris-virginica
27            5.2          3.5           1.5          0.2      Iris-setosa
134           6.1          2.6           5.6          1.4   Iris-virginica
17            5.1          3.5           1.4          0.3      Iris-setosa
59            5.2          2.7           3.9          1.4  Iris-versicolor
114           5.8          2.8           5.1          2.4   Iris-virginica
97            6.2          2.9           4.3          1.3  Iris-versicolor
73            6.1          2.8           4.7          1.2  Iris-versicolor

Cleaning

In [10]:
# Displaying the shape of the train and test dataframes
print("Shape of train dataset:", train.shape)
print("Shape of test dataset:", test.shape)

# Checking for missing values
print("\nMissing values in train dataset:\n", train.isnull().sum())
print("\nMissing values in test dataset:\n", test.isnull().sum())

# Checking data types
print("\nData types of train dataset:\n", train.dtypes)
print("\nData types of test dataset:\n", train.dtypes)

# Displaying descriptive statistics
print("\nDescriptive statistics of train dataset:\n", train.describe())
print("\nDescriptive statistics of test dataset:\n", test.describe())

# Dropping duplicate rows (if any) - Iris dataset has no duplicates, this is for demonstration
train_cleaned = train.drop_duplicates()
test_cleaned = test.drop_duplicates()
print("\nShape of train dataset after dropping duplicates:", train_cleaned.shape)
print("Shape of test dataset after dropping duplicates:", test_cleaned.shape)

# Example of renaming columns (if needed)
train_renamed = train.rename(columns={'sepal length (cm)': 'sepal_length'})
print("\nTrain dataset with renamed column:\n", train_renamed.head())

# Example of handling outliers (e.g., using IQR - not strictly necessary for this dataset)
numerical_train = train.select_dtypes(include=np.number) # Select only numerical columns for quantile calculation

Q1 = numerical_train.quantile(0.25)
Q3 = numerical_train.quantile(0.75)
IQR = Q3 - Q1
train_outliers_removed = train[~((numerical_train < (Q1 - 1.5 * IQR)) |(numerical_train > (Q3 + 1.5 * IQR))).any(axis=1)]
print("\nShape of train dataset after removing potential outliers:", train_outliers_removed.shape)

Shape of train dataset: (120, 5)
Shape of test dataset: (30, 5)

Missing values in train dataset:
 sepal length    0
sepal width     0
petal length    0
petal width     0
class           0
dtype: int64

Missing values in test dataset:
 sepal length    0
sepal width     0
petal length    0
petal width     0
class           0
dtype: int64

Data types of train dataset:
 sepal length    float64
sepal width     float64
petal length    float64
petal width     float64
class            object
dtype: object

Data types of test dataset:
 sepal length    float64
sepal width     float64
petal length    float64
petal width     float64
class            object
dtype: object

Descriptive statistics of train dataset:
        sepal length  sepal width  petal length  petal width
count    120.000000   120.000000    120.000000   120.000000
mean       5.794167     3.075833      3.616667     1.145000
std        0.853790     0.462728      1.807702     0.782889
min        4.300000     2.000000      1.000000   

In [11]:
train

sepal length  sepal width  petal length  petal width            class
121           5.6          2.8           4.9          2.0   Iris-virginica
10            5.4          3.7           1.5          0.2      Iris-setosa
36            5.5          3.5           1.3          0.2      Iris-setosa
22            4.6          3.6           1.0          0.2      Iris-setosa
90            5.5          2.6           4.4          1.2  Iris-versicolor
..            ...          ...           ...          ...              ...
9             4.9          3.1           1.5          0.1      Iris-setosa
139           6.9          3.1           5.4          2.1   Iris-virginica
24            4.8          3.4           1.9          0.2      Iris-setosa
13            4.3          3.0           1.1          0.1      Iris-setosa
107           7.3          2.9           6.3          1.8   Iris-virginica

[120 rows x 5 columns]

In [12]:
test

sepal length  sepal width  petal length  petal width            class
45            4.8          3.0           1.4          0.3      Iris-setosa
127           6.1          3.0           4.9          1.8   Iris-virginica
91            6.1          3.0           4.6          1.4  Iris-versicolor
108           6.7          2.5           5.8          1.8   Iris-virginica
29            4.7          3.2           1.6          0.2      Iris-setosa
124           6.7          3.3           5.7          2.1   Iris-virginica
69            5.6          2.5           3.9          1.1  Iris-versicolor
149           5.9          3.0           5.1          1.8   Iris-virginica
50            7.0          3.2           4.7          1.4  Iris-versicolor
116           6.5          3.0           5.5          1.8   Iris-virginica
125           7.2          3.2           6.0          1.8   Iris-virginica
40            5.0          3.5           1.3          0.3      Iris-setosa
54            6.5          2.8           4.6          1.5  Iris-versicolor
58            6.6          2.9           4.6          1.3  Iris-versicolor
98            5.1          2.5           3.0          1.1  Iris-versicolor
67            5.8          2.7           4.1          1.0  Iris-versicolor
145           6.7          3.0           5.2          2.3   Iris-virginica
103           6.3          2.9           5.6          1.8   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
120           6.9          3.2           5.7          2.3   Iris-virginica
95            5.7          3.0           4.2          1.2  Iris-versicolor
77            6.7          3.0           5.0          1.7  Iris-versicolor
132           6.4          2.8           5.6          2.2   Iris-virginica
27            5.2          3.5           1.5          0.2      Iris-setosa
134           6.1          2.6           5.6          1.4   Iris-virginica
17            5.1          3.5           1.4          0.3      Iris-setosa
59            5.2          2.7           3.9          1.4  Iris-versicolor
114           5.8          2.8           5.1          2.4   Iris-virginica
97            6.2          2.9           4.3          1.3  Iris-versicolor
73            6.1          2.8           4.7          1.2  Iris-versicolor